#+title: Stop Orders
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: ~/.emacs.d/org-themes/src/readtheorg_inline/readtheorg_inline.theme

Bottom line up front:

#+begin_quote
Stop orders are a type of /price-contingent/ order mainly used to limit losses, however they can also be used in momentum trading strategies.
#+end_quote

* Examples: Limiting Losses

** You own stock

Let's say you own 100 shares of XOM, and XOM's price per share today is $80.  This means your position value is $8000.  What if you wanted to limit your losses to $1000.  You will lose $1000 if the stock falls to $70 per share.  Your broker offers *stop sell* orders to allow you to attempt to exit your position at $70.

If you submit a stop sell order for $100 XOM with a stop price of $70, your broker will hold the sell order until the market price of XOM touches $70.  At that point your broker will submit a market sell 100 XOM to the exchange for you.  Hopefully, you will exit your position near $70.


** You are short stock


Now, assume you are short 500 shares of BA.  BA's price per share is now $180.  You want to limit your losses to $10,000, which occurs if the price rises to $200 per share. So you submit a stop buy order with a stop price of $200.  If BA rises to $200, your broker will submit to the exchange a market buy 500 BA shares on your behalf.  Again, since it is a market buy, there is no guarantee of what price you will receive at the exchange.


** Key points

1.  If the order has not yet been triggered, it is held by your broker and it does not sit in an exchange's limit order book.
2.  There is no guarantee you will sell the stock for $70.  To get a guarantee we need to use options.
3.  You cannot submit a stop order to your broker---you can submit a stop buy or a stop sell.  

* Difference from Limit Orders

You might think this order type is redundant--why not just use limit orders?

Consider the limit sell and stop sell:

-  Stop sell:  sell the stock if the price falls to some point.
-  Limit sell: sell the stock at no lower than some price (that is if the stock /rises/ to some value).

Let's revisit the first example, you own 100 XOM and want to sell if the price falls from $80 to $70 per share.  You try and put a limit sell order for 100 XOM at a limit price of $70 per share.  You send this order to the exchange and what happens?  It is immediately executed at around $80---which is /no lower/ than $70.  

Now, consider the limit buy and stop buy:

-  Stop buy:  buy the stock if the price rises to some point.
-  Limit buy: buy the stock at no higher than some price (that is if the stock /falls/ to some value).

Assume again we are short 500 shares of BA at $180 per share.  If we enter a limit buy for 500 BA shares at $200, the order will again be immediately executed at around $180.  Our limit buy simply said buy no higher than $200.

So stop and limit orders are not redundant, and each is useful in unique circumstances.

* Use in Momentum Trading Strategies

Momentum trading is a class of algorithmic trading strategy where you bet that a given asset will continue its present path.  That is, if a stock is increasing you bet it will keep increasing.  Similarly, you think declining stocks may continue to decline.

Say NVDA is at $100, and you think if it rises by 5% you should buy.  You can enter a stop buy order with a $105 stop price.  Note, we are calling this /stop/ order but it is actually opening the position.  Consider again you could not have used a limit order to enter this trade.  Similarly you can use stop sell orders to initiate a short position based on momentum.

* The Stop-Limit Order

When a stop order is triggered it is sent from your broker to the exchange as a market order. A /stop-limit/ order is a stop order that once triggered, is sent to the exchange as a limit order.  Consider our first example where you own 100 shares of XOM, XOM's price per share today is $80, and you want to sell if the stock falls to $70.  You can enter a stop-limit order with a $70 stop-limit.  If the stock falls to $70, your broker will send a limit sell 100 XOM to the exchange. The downside of this is if the bid moves below $70 before your order reaches the exchange your order will not be executed.  So you may never exit the trade---which is a flaw in a loss mitigation strategy.  In the authors opinion, never use stop-limit orders.  It is better to, in this case, buy a put option struck at $70.
